name: open-musiclm
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=22.3.1
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.11.0+cu113
    - torchvision==0.12.0+cu113 
    - torchaudio==0.11.0+cu113 
    - git+https://github.com/lucidrains/audiolm-pytorch.git
    - einops>=0.4
    - vector-quantize-pytorch>=0.10.15
    - librosa==0.10.0
    - torchlibrosa==0.1.0
    - ftfy
    - tqdm
    - transformers
    - encodec==0.1.1
    - gdown